sudo: false

notifications:
  irc:
    channels:
      - "chat.freenode.net#lichess"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack:
    rooms:
      - secure: "LdcLNNeKKSOlHzX8n2+hqFZw6QqnKBfP+/BFtgEYe4QPb25sKxlxwnf28T7AVkf1F+/OA9KMcL+ZsCcXS6kB/0mI3P49hJfQT9XyUSvfpI81196oiEkCM5I+xDuzi5ejR0Sxt80OUOqw+vHOZYzGVtlfxtTbNxcT94V8j141hwY="
    on_success: change
    on_failure: always
  email: false

env:
  global:
   - secure: "VkgJ78marLdG8JQrWV3UhcxXyWmdy6BV3gYLTyXpK2ltPA4vGkFilZDc8hMx2VhYeeTXyvXB+PM4xkB40PUnDlmNXIWQlG7IxKIb/zxwUVS+WcvAzM6yqEV9B/UbZO+Mgp2Hl4/F1lMoIpdQ0tkRvHmfw01L9VDrQs4Otdmd38o=" # GITHUB_API_TOKEN

branches:
  except:
   - l10n_master

git:
  depth: 3
  submodules: false

install: ./bin/submodule-setup.sh

jobs:
  include:
    # Build server
    - stage: test
      language: scala
      jdk: openjdk8
      before_install:
       - echo "autoformat=false" > $HOME/.scalariform.conf
      script: sbt test:compile test stage
      after_success:
       - git log -n 1 --pretty=oneline > commit.txt
       - tar -zcf "lila-server-${TRAVIS_BRANCH}.tar.gz" target/universal/stage LICENSE COPYING.md README.md commit.txt
      before_cache:
       - find $HOME/.ivy2/cache -name 'ivydata-*.properties' -delete
       - find $HOME/.sbt -name '*.lock' -delete
       - rm -rf $HOME/.sbt/0.13/dependency/module/dynamic
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
      addons:
        artifacts:
          bucket: lichess.org
          s3_region: eu-west-1
          cache_control: public
          paths: $(ls lila-server-*.tar.gz)
          target_paths: lila
          key:
            secure: "lv+M2bXAjuKfl3ta8PDcljURpmnGjoNnf79dcryvZ6H3bT0FrW3rNKIxXqO4v/daZAuY3o+/nTOjg552ghFDmAqvygA9WF2pLuKd5Q877AtD54tkcr53oYLooBEaQ7nAkJnHl2NM8nii3mvksZ4+1ss7ww535u53sWu+a7PwQwI="
          secret:
            secure: "yoErYc4k/g00cP+P2jNZ3v4lAJnEuspE1j7DB9U42leWEGGgyqvKhNJLR5u/JLpxz2+UX6lmjlN0D3SLT4SVLpdacNvRdjRNVpazWpkOsxmKwiQRqjAQl/aoydW6JqUrFoIyH+HzSRdJdxLeXerEJdsTMXHRfHiBPaXWZzHnxY0="

    # Build assets
    - stage: test
      language: node_js
      node_js: "10"
      before_install:
       - yarn --version
       - yarn global add gulp-cli
      script: ./ui/build prod
      after_success:
       - git log -n 1 --pretty=oneline > commit.txt
       - tar -zcf "lila-assets-${TRAVIS_BRANCH}.tar.gz" public LICENSE COPYING.md README.md commit.txt
      cache:
        directories:
          - $HOME/.cache/yarn
      addons:
        apt:
          packages:
            - parallel
        artifacts:
          bucket: lichess.org
          s3_region: eu-west-1
          cache_control: public
          paths: $(ls lila-assets-*.tar.gz)
          target_paths: lila
          key:
            secure: "lv+M2bXAjuKfl3ta8PDcljURpmnGjoNnf79dcryvZ6H3bT0FrW3rNKIxXqO4v/daZAuY3o+/nTOjg552ghFDmAqvygA9WF2pLuKd5Q877AtD54tkcr53oYLooBEaQ7nAkJnHl2NM8nii3mvksZ4+1ss7ww535u53sWu+a7PwQwI="
          secret:
            secure: "yoErYc4k/g00cP+P2jNZ3v4lAJnEuspE1j7DB9U42leWEGGgyqvKhNJLR5u/JLpxz2+UX6lmjlN0D3SLT4SVLpdacNvRdjRNVpazWpkOsxmKwiQRqjAQl/aoydW6JqUrFoIyH+HzSRdJdxLeXerEJdsTMXHRfHiBPaXWZzHnxY0="
