sudo: false
language: scala

# https://docs.travis-ci.com/user/notifications/#IRC-notification
notifications:
  irc:
    channels:
      - "chat.freenode.net#lichess"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack:
    rooms:
      - secure: "I9aVV+C0cFCUxXgt8gtSHBFPBRBN6fI36n7l7ZtmN2bR+1L1gXw1uFwZBPEPJtyWvGGKRTwk5diPySOTGE0sjDczEXDLuNht36v+ehnqmg6sVfOkQcqaLt/LhGkcaBJ/85e+hknEMuOOtQvDqlcQ1P7xckW2Mj7l211donlrU94="
    on_success: change
    on_failure: always
  email: false

# https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
jdk:
  - openjdk8
  - openjdk13

before_cache:
 - find $HOME/.ivy2/cache -name 'ivydata-*.properties' -delete
 - find $HOME/.sbt -name '*.lock' -delete
 - rm -rf $HOME/.sbt/*/dependency/module/dynamic
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt test
