blank_issues_enabled: false
contact_links:
  - name: Mobile app
    url: https://github.com/veloce/lichobile/issues
    about: Issues for the mobile app are tracked in a separate repository. Please check for duplicates first.
  - name: Support
    url: https://discord.gg/pw6Efvk
    about: GitHub issues are meant for tracking enhancements and bugs, not general support. Instead, search the Wiki, Lichess Forum, StackOverflow, or join our Discord.
