name: Lint code

on:
  push:
    branches-ignore:
      - 'l10n_master2'
  pull_request:
    paths-ignore:
      - 'translation/dest/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn run lint
      - run: yarn run check-format
