name: Build server

on:
  push:
    paths:
    - 'app/**'
    - 'conf/**'
    - 'modules/**'
    - 'project/**'
    - 'build.sbt'
    branches-ignore:
    - 'l10n_master'
  pull_request:
    paths:
    - 'app/**'
    - 'conf/**'
    - 'modules/**'
    - 'project/**'
    - 'build.sbt'
    branches-ignore:
    - 'l10n_master'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: echo "autoformat=false" > ~/.scalariform.conf
    - uses: olafurpg/setup-scala@49fc8c734ef6916b4e1da8ba8d81bb26a2b46a06 # v7
      with:
        java-version: openjdk@1.13
    - run: ./lila test
    - run: ./lila dist
    - run: unzip target/universal/lila-3.0.zip
    - run: cp LICENSE COPYING.md README.md lila-3.0 && git log -n 1 --pretty=oneline > lila-3.0/commit.txt
    - run: du -d2 -h ~
    - uses: actions/upload-artifact@v1
      with:
        name: lila-server
        path: lila-3.0
